# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop, iracing_leds ]
  pull_request:
    branches: [ main, develop, iracing_leds ]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm uninstall @abandonware/noble && npm install https://github.com/mplutka/noble
    #- run: npm uninstall node-irsdk && npm install https://github.com/sabifa/node-irsdk
    #- run: npm uninstall f1-telemetry-client && npm install https://github.com/mplutka/f1-telemetry-client
    - run: npm install && npm run build && npm run pack

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          dist/*

     
          

